apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv-volume1
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/pg1"
