apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: k8s-day2
data:
  prometheus.yml: |
    global:
      scrape_interval:     10s

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']

      - job_name: 'csvserver'
        static_configs:
          - targets: ['csvserver.k8s-day2.svc.cluster.local:80']